### ISSUE TITLE
Resize mode not resizing (with custom keybinds?)

### ISSUE THREAD

**Issue by tarek-y-ismail** [miracle-wm-org/miracle-wm#290]
Launching resize mode with `super + r` then `super + left/right/up/down` does not seem to work on my end. My test scenario was launching both element and firefox and trying to resize element via the aforementioned shortcuts. My current suspicion is  that my keybind overrides might be the culprit.

<details> <summary> Here's the entirety of my config since Github doesn't support attaching yaml files .... </summary>

```
action_key: meta

terminal: gnome-terminal

custom_actions:
  - command: wofi --show=drun
    action: down
    modifiers:
      - primary
    key: KEY_SPACE
  - command: grim
    action: down
    key: KEY_SYSRQ

border:
  size: 2
  color: 0xbd93f9ff
  focus_color: 0x50fa7bff

startup_apps:
  - command: waybar
    restart_on_death: true
  - command: swaybg -i /home/tarek/tsutomu-nihei-wallpapers/18\ -\ ar0Qp.jpg --mode fit

animations:
    - event: window_open
      type: grow
      function: ease_in_out_back
      duration: 0.1
    - event: window_move
      type: slide
      function: ease_in_out_back
      duration: 0.1
    - event: window_close
      type: shrink
      function: ease_out_back
      duration: 0.1
    - event: workspace_switch
      type: slide
      function: ease_out_sine
      duration: 0.1

default_action_overrides:
  - name: toggle_floating
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_F
  - name: move_up
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_K
  - name: move_down
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_J
  - name: move_right
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_L
  - name: move_left
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_H
  - name: select_up
    action: down
    modifiers:
      - primary
    key: KEY_K
  - name: select_down
    action: down
    modifiers:
      - primary
    key: KEY_J
  - name: select_right
    action: down
    modifiers:
      - primary
    key: KEY_L
  - name: select_left
    action: down
    modifiers:
      - primary
    key: KEY_H

inner_gaps:
  x: 0
  y: 0

outer_gaps:
  x: 0
  y: 0
```
 </details>
