### ISSUE TITLE
Rendering issue with Qt dialog windows

### ISSUE THREAD

**Issue by Sunderland93** [miracle-wm-org/miracle-wm#539]
Hello. When opening a dialog window (in this case, folder properties) in the PCmanFM-Qt file manager, it is drawn normally, without any problems, but if another window is opened, for example, a terminal, the dialog window disappears or is drawn in pieces, and when trying to switch it to floating mode, it begins to be drawn behind other windows. I am attaching a video with the described problem.

Distro: Debian 13-based (TileOS)
MiracleWM: 0.5.2
Mir: 2.20.2

https://github.com/user-attachments/assets/f35f5a0b-7037-4ec6-a4eb-b063faf7217c

**Comment by mattkae** [comment]
Oops looks like a clip area issue! I wonder if this is fixed on latest `develop`. I will add this to the pile to fix before 0.6.0 (which should arrive before end of month!)

**Comment by mattkae** [comment]
This should be fixed on latest, let me know!

**Comment by Sunderland93** [comment]
I've built Miracle 0.6.1 with Mir 2.21.1, and when I open PCManFM-Qt About dialog - MiracleWM  is crashing. It is also crash sometimes when I open Alacritty. This is messages in `journalctl /usr/bin/miracle-wm` output

<img width="2050" height="1164" alt="Image" src="https://github.com/user-attachments/assets/330b2a4b-d523-44c2-853d-a1be6f223131" />

**Comment by mattkae** [comment]
Which version of PCmanFM-Qt was this run with? I wonder if I am running an earlier version that works ok on Ubuntu

**Comment by Sunderland93** [comment]
PCManFM-Qt version 2.1.0 built with Qt 6.8.2

**Comment by Sunderland93** [comment]
Also this is my config 

```
terminal: alacritty

# Autostart section
startup_apps:
    - command: /usr/bin/mate-polkit
      restart_on_death: true
    - command: bash -c ~/.azotebg
      restart_on_death: true
    - command: wl-paste --watch cliphist store &
    - command: wl-paste --watch pkill -RTMIN+9 waybar &
    - command: nwg-drawer -r
      restart_on_death: true
    - command: pcmanfm-qt -d
      in_systemd_scope: true
    - command: playerctl -a metadata --format \'{{status}} {{title}}\' --follow | while read line; do pkill -RTMIN+5 waybar; done &

border:
  size: 2
  color: 0xa5adcb
  focus_color: 0x8aadf4

enable_animations: true

animations:
    - event: window_open
      type: grow
      function: ease_in_out_back
      duration: 0.25
    - event: window_move
      type: slide
      function: ease_in_out_back
      duration: 0.25
    - event: window_close
      type: shrink
      function: ease_out_back
      duration: 0.25
    - event: workspace_switch
      type: slide
      function: ease_out_sine
      duration: 0.175

workspaces:
    - number: 0
      layout: tiled
    - number: 1
      layout: tiled
    - number: 2
      layout: tiled
    - number: 3
      layout: tiled
    - number: 4
      layout: tiled
    - number: 5
      layout: tiled
    - number: 6
      layout: tiled
    - number: 7
      layout: tiled
    - number: 8
      layout: tiled
    - number: 9
      layout: tiled

default_action_overrides:
    - name: toggle_floating
      action: down
      modifiers:
        - primary
        - shift
      key: KEY_SPACE

custom_actions:
    - command: wofi
      action: down
      modifiers:
        - primary
      key: KEY_D
    - command: nwg-bar
      action: down
      modifiers:
        - primary
        - shift
      key: KEY_E
    - command: /usr/share/tileos/scripts/brightness.sh up
      action: down
      modifiers:
        - function
      key: KEY_BRIGHTNESSUP
    - command: /usr/share/tileos/scripts/brightness.sh down
      action: down
      modifiers:
        - function
      key: KEY_BRIGHTNESSDOWN
    - command: /usr/share/tileos/scripts/mic-mute.sh
      action: down
      modifiers:
        - function
      key: KEY_MICMUTE
    - command: playerctl play-pause
      action: down
      modifiers:
        - function
      key: KEY_PLAYPAUSE
    - command: playerctl next
      action: down
      modifiers:
        - function
      key: KEY_NEXTSONG
    - command: playerctl previous
      action: down
      modifiers:
        - function
      key: KEY_PREVIOUSSONG
    - command: pulsemixer --change-volume +5
      action: down
      modifiers:
        - function
      key: KEY_VOLUMEUP
    - command: pulsemixer --change-volume -5
      action: down
      modifiers:
        - function
      key: KEY_VOLUMEDOWN
    - command: pulsemixer --toggle-mute
      action: down
      modifiers:
        - function
      key: KEY_MUTE
```
